# Generated by Django 5.1.5 on 2025-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
