# Generated by Django 5.1.5 on 2025-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_order_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='homePage.book'),
        ),
    ]
