# Generated by Django 5.1.5 on 2025-07-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counts',
            field=models.JSONField(default=dict),
        ),
    ]
