# Generated by Django 5.1.5 on 2025-07-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerPhone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
