# Generated by Django 5.1.5 on 2025-07-31 08:54

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_order_customerphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
