# Generated by Django 5.1.5 on 2025-08-04 07:13

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'نظرات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'کاربر ها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AddField(
            model_name='book',
            name='available_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=100, verbose_name='نام کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='homePage.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hotDeal',
            field=models.BooleanField(default=False, verbose_name='پشنهاد ویژه'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود بودن'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='production_year',
            field=models.CharField(default='1404', max_length=11, verbose_name='سال انتشار'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicated_from',
            field=models.CharField(default='فرهنگ و قلم', max_length=100, verbose_name='انتشاراتی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_count',
            field=models.BigIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز رسانی شده در تاریخ :'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نوسنده نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bodyText',
            field=models.TextField(max_length=900, verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در :'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='relatedBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.book', verbose_name='کتاب مربوطه'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='favBooks',
            field=models.ManyToManyField(to='homePage.book', verbose_name='کتاب های مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uniqueMail',
            field=models.EmailField(default='<EMAIL>', max_length=254, unique=True, verbose_name='ایمیل یکتا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='', max_length=1000, verbose_name='آدرس ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='counts',
            field=models.JSONField(default=dict, verbose_name='تعداد آیتم های سفارش شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='ایجاد شده در :'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerName',
            field=models.CharField(default='anonymous', max_length=100, verbose_name='نام سفارش دهنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerPhone',
            field=models.CharField(default='', max_length=20, verbose_name='شماره تلفن سفارش دهنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='homePage.book', verbose_name='کتاب ها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.PositiveIntegerField(default=0, verbose_name='کد یکتای پرداخت از سمت زرین پال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='مبلغ کل سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش دهنده'),
        ),
    ]
