# Generated by Django 5.1.5 on 2025-07-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_Register', '0005_alter_randomcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomcode',
            name='value',
            field=models.BigIntegerField(default=2231056),
        ),
    ]
