# Generated by Django 5.1.5 on 2025-08-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_Register', '0007_alter_randomcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomcode',
            name='value',
            field=models.BigIntegerField(default=4875299),
        ),
    ]
